# Generated by Django 4.0.4 on 2022-05-08 01:05

from django.db import migrations, models
import django_quill.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('introduction', django_quill.fields.QuillField()),
                ('content', django_quill.fields.QuillField()),
                ('email_address', models.EmailField(max_length=200)),
                ('twitter_url', models.CharField(max_length=200)),
                ('discord_id', models.CharField(max_length=200)),
                ('github_url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Stack',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('cover_image', imagekit.models.fields.ProcessedImageField(upload_to='projects/')),
                ('description', django_quill.fields.QuillField()),
                ('link', models.URLField()),
                ('tech_stack', models.ManyToManyField(to='portfolio.stack')),
            ],
        ),
    ]
